# Generated by Django 2.2.3 on 2019-08-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='repo_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='script',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='PipeLineItem',
        ),
        migrations.DeleteModel(
            name='PipeLineItemType',
        ),
    ]
