dist: xenial

addons:
  firefox: latest

language: python

python:
- "3.7"

# setup environment
env:
- DJANGO_VERSION=2.2

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

# install dependencies
install:
- pip install -r requirements.txt
- pip install codecov

# run test scripts
script:
- export MOZ_HEADLESS=1
- coverage run --source='.' manage.py test

# Push the results back to codecov
after_success:
- codecov
