# Generated by Django 2.2.3 on 2019-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='repo_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
