# Generated by Django 2.2.4 on 2019-09-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pipelineresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresults',
            name='config',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pipelineresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pipelineresults',
            name='log',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pipelineresults',
            name='pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.PipeLine'),
        ),
        migrations.AddField(
            model_name='pipelineresults',
            name='results',
            field=models.CharField(default='In progress', max_length=30),
        ),
        migrations.AddField(
            model_name='pipelineresults',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
