# Generated by Django 2.2.3 on 2019-08-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190820_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='repo_url',
            field=models.URLField(default=''),
        ),
    ]
