# Generated by Django 2.2.4 on 2019-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190918_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineresults',
            old_name='results',
            new_name='status',
        ),
    ]
