# Generated by Django 2.2.4 on 2019-09-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190918_1946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PipeLineResults',
            new_name='PipeLineResult',
        ),
    ]
