# Generated by Django 2.2.4 on 2019-09-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190921_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineresult',
            name='pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PipeLine'),
        ),
    ]
