# Generated by Django 2.2.4 on 2019-09-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190921_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='command',
            field=models.TextField(default=''),
        ),
    ]
