# Generated by Django 2.2.4 on 2019-10-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_pipelineresult_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='triggered_by',
            field=models.TextField(default=''),
        ),
    ]
