# Generated by Django 2.2.4 on 2019-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_pipelineresult_triggered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='is_github_pipeline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='repository_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='site_private',
            field=models.BooleanField(default=False),
        ),
    ]
