# Generated by Django 2.2.4 on 2019-10-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20191013_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='commit_sha',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
