# Generated by Django 2.2.4 on 2019-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_pipeline_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='build_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
