# Generated by Django 2.2.4 on 2019-11-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_pipelineresult_build_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='type',
            field=models.TextField(default='push'),
        ),
    ]
