# Generated by Django 2.2.4 on 2019-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20191101_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineresult',
            name='log_file_name',
            field=models.TextField(default=''),
        ),
    ]
